export const screenMatrix = [
  { id: 'MH-01', path: '/auth/login', roles: ['PUBLIC'], title: 'Đăng nhập' },
  { id: 'MH-02', path: '/auth/register', roles: ['PUBLIC'], title: 'Đăng ký khách hàng' },
  { id: 'MH-03', path: '/account/change-password', roles: ['CUSTOMER', 'CASHIER', 'WAREHOUSE', 'MANAGER'], title: 'Đổi mật khẩu' },
  { id: 'MH-04', path: '/cashier', roles: ['CASHIER'], title: 'Dashboard thu ngân' },
  { id: 'MH-05', path: '/cashier', roles: ['CASHIER'], title: 'Mở và đóng ca' },
  { id: 'MH-06', path: '/cashier/pos', roles: ['CASHIER'], title: 'POS và giỏ hàng' },
  { id: 'MH-07', path: '/cashier/receipts/demo-invoice', roles: ['CASHIER'], title: 'Thanh toán và hóa đơn' },
  { id: 'MH-08', path: '/cashier/invoices', roles: ['CASHIER', 'MANAGER'], title: 'Tra cứu hóa đơn' },
  { id: 'MH-09', path: '/cashier/returns/demo-invoice', roles: ['CASHIER'], title: 'Đổi trả hàng' },
  { id: 'MH-10', path: '/manager/suppliers', roles: ['MANAGER'], title: 'Quản lý nhà cung cấp' },
  { id: 'MH-11', path: '/warehouse/receiving/new', roles: ['WAREHOUSE'], title: 'Lập phiếu nhập' },
  { id: 'MH-12', path: '/warehouse/receiving', roles: ['WAREHOUSE'], title: 'Danh sách và xác nhận nhập kho' },
  { id: 'MH-13', path: '/warehouse/inventory', roles: ['WAREHOUSE', 'MANAGER'], title: 'Tồn kho, lô và cảnh báo' },
  { id: 'MH-14', path: '/warehouse/stocktakes', roles: ['WAREHOUSE'], title: 'Kiểm kê kho' },
  { id: 'MH-15', path: '/manager/stocktakes', roles: ['MANAGER'], title: 'Phê duyệt điều chỉnh kho' },
  { id: 'MH-16', path: '/manager/products', roles: ['MANAGER'], title: 'Quản lý sản phẩm' },
  { id: 'MH-17', path: '/manager/products/pricing', roles: ['MANAGER'], title: 'Cập nhật giá bán' },
  { id: 'MH-18', path: '/manager/promotions', roles: ['MANAGER'], title: 'Quản lý khuyến mãi' },
  { id: 'MH-19', path: '/manager/employees', roles: ['MANAGER'], title: 'Quản lý nhân viên' },
  { id: 'MH-20', path: '/manager/accounts', roles: ['MANAGER'], title: 'Quản lý tài khoản và role' },
  { id: 'MH-21', path: '/manager/customers', roles: ['MANAGER'], title: 'Quản lý khách hàng thành viên' },
  { id: 'MH-22', path: '/manager/audit-logs', roles: ['MANAGER'], title: 'Nhật ký thao tác' },
  { id: 'MH-23', path: '/manager/reports/revenue', roles: ['MANAGER'], title: 'Báo cáo doanh thu' },
  { id: 'MH-24', path: '/manager/reports/merchandise', roles: ['MANAGER'], title: 'Báo cáo hàng hóa và nhập kho' },
  { id: 'MH-25', path: '/manager/reports/workforce', roles: ['MANAGER'], title: 'Báo cáo nhân viên và ca' },
  { id: 'MH-26', path: '/products', roles: ['PUBLIC', 'CUSTOMER'], title: 'Danh mục sản phẩm và ưu đãi' },
  { id: 'MH-27', path: '/customer/history', roles: ['CUSTOMER'], title: 'Lịch sử mua hàng và điểm' },
  { id: 'MH-28', path: '/customer/profile', roles: ['CUSTOMER'], title: 'Hồ sơ khách hàng' },
];
