SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
GO

DROP INDEX IF EXISTS UX_CA_LAM_VIEC_MaNV_OPEN ON dbo.CA_LAM_VIEC;
GO

CREATE UNIQUE INDEX UX_CA_LAM_VIEC_MaNV_OPEN
    ON dbo.CA_LAM_VIEC (MaNV)
    INCLUDE (MaCa, GioBatDau, TienDauCa)
    WHERE TrangThai = 'OPEN';
GO

DROP INDEX IF EXISTS UX_GIAO_DICH_KHO_SALE_MaThamChieu_MaLo ON dbo.GIAO_DICH_KHO;
GO

CREATE UNIQUE INDEX UX_GIAO_DICH_KHO_SALE_MaThamChieu_MaLo
    ON dbo.GIAO_DICH_KHO (MaThamChieu, MaLo)
    INCLUDE (MaSP, SoLuongBienDong, ThoiGian, MaNV)
    WHERE LoaiGiaoDich = 'SALE';
GO

DROP INDEX IF EXISTS UX_THANH_TOAN_SUCCESS_MaHD ON dbo.THANH_TOAN;
GO

CREATE UNIQUE INDEX UX_THANH_TOAN_SUCCESS_MaHD
    ON dbo.THANH_TOAN (MaHD)
    INCLUDE (PhuongThuc, SoTien, ThoiGian, MaGiaoDichNgoai)
    WHERE TrangThai = 'SUCCESS';
GO

PRINT 'Sale shift, stock movement and successful payment indexes are ready.';
GO
