SET NOCOUNT ON;
SET XACT_ABORT ON;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
GO

DROP INDEX IF EXISTS IX_PHIEU_TRA_MaHD_TrangThai_NgayTra ON dbo.PHIEU_TRA;
GO

CREATE INDEX IX_PHIEU_TRA_MaHD_TrangThai_NgayTra
    ON dbo.PHIEU_TRA (MaHD, TrangThai, NgayTra DESC)
    INCLUDE (MaPT, MaNV, TongTienHoan);
GO

DROP INDEX IF EXISTS UX_GIAO_DICH_KHO_RETURN_MaThamChieu_MaLo ON dbo.GIAO_DICH_KHO;
GO

CREATE UNIQUE INDEX UX_GIAO_DICH_KHO_RETURN_MaThamChieu_MaLo
    ON dbo.GIAO_DICH_KHO (MaThamChieu, MaLo)
    INCLUDE (MaSP, SoLuongBienDong, ThoiGian, MaNV)
    WHERE LoaiGiaoDich = 'RETURN';
GO

PRINT 'Return lookup and stock-movement invariant indexes are ready.';
GO
