SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF OBJECT_ID('dbo.NHAT_KY_HE_THONG', 'U') IS NOT NULL DROP TABLE dbo.NHAT_KY_HE_THONG;
IF OBJECT_ID('dbo.CHI_TIET_PHIEU_TRA', 'U') IS NOT NULL DROP TABLE dbo.CHI_TIET_PHIEU_TRA;
IF OBJECT_ID('dbo.PHIEU_TRA', 'U') IS NOT NULL DROP TABLE dbo.PHIEU_TRA;
IF OBJECT_ID('dbo.THANH_TOAN', 'U') IS NOT NULL DROP TABLE dbo.THANH_TOAN;
IF OBJECT_ID('dbo.CHI_TIET_XUAT_LO', 'U') IS NOT NULL DROP TABLE dbo.CHI_TIET_XUAT_LO;
IF OBJECT_ID('dbo.CHI_TIET_HOA_DON', 'U') IS NOT NULL DROP TABLE dbo.CHI_TIET_HOA_DON;
IF OBJECT_ID('dbo.HOA_DON', 'U') IS NOT NULL DROP TABLE dbo.HOA_DON;
IF OBJECT_ID('dbo.GIAO_DICH_KHO', 'U') IS NOT NULL DROP TABLE dbo.GIAO_DICH_KHO;
IF OBJECT_ID('dbo.CHI_TIET_KIEM_KE', 'U') IS NOT NULL DROP TABLE dbo.CHI_TIET_KIEM_KE;
IF OBJECT_ID('dbo.KIEM_KE', 'U') IS NOT NULL DROP TABLE dbo.KIEM_KE;
IF OBJECT_ID('dbo.CHI_TIET_PHIEU_NHAP', 'U') IS NOT NULL DROP TABLE dbo.CHI_TIET_PHIEU_NHAP;
IF OBJECT_ID('dbo.LO_HANG', 'U') IS NOT NULL DROP TABLE dbo.LO_HANG;
IF OBJECT_ID('dbo.PHIEU_NHAP', 'U') IS NOT NULL DROP TABLE dbo.PHIEU_NHAP;
IF OBJECT_ID('dbo.NHA_CUNG_CAP', 'U') IS NOT NULL DROP TABLE dbo.NHA_CUNG_CAP;
IF OBJECT_ID('dbo.KHUYEN_MAI_SAN_PHAM', 'U') IS NOT NULL DROP TABLE dbo.KHUYEN_MAI_SAN_PHAM;
IF OBJECT_ID('dbo.KHUYEN_MAI', 'U') IS NOT NULL DROP TABLE dbo.KHUYEN_MAI;
IF OBJECT_ID('dbo.SAN_PHAM', 'U') IS NOT NULL DROP TABLE dbo.SAN_PHAM;
IF OBJECT_ID('dbo.LOAI_SAN_PHAM', 'U') IS NOT NULL DROP TABLE dbo.LOAI_SAN_PHAM;
IF OBJECT_ID('dbo.CA_LAM_VIEC', 'U') IS NOT NULL DROP TABLE dbo.CA_LAM_VIEC;
IF OBJECT_ID('dbo.TAI_KHOAN', 'U') IS NOT NULL DROP TABLE dbo.TAI_KHOAN;
IF OBJECT_ID('dbo.KHACH_HANG', 'U') IS NOT NULL DROP TABLE dbo.KHACH_HANG;
IF OBJECT_ID('dbo.NHAN_VIEN', 'U') IS NOT NULL DROP TABLE dbo.NHAN_VIEN;
IF OBJECT_ID('dbo.VAI_TRO', 'U') IS NOT NULL DROP TABLE dbo.VAI_TRO;
GO
