SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

CREATE TABLE dbo.VAI_TRO (
    MaVaiTro VARCHAR(20) NOT NULL,
    TenVaiTro NVARCHAR(50) NOT NULL,
    MoTa NVARCHAR(255) NULL,
    CONSTRAINT PK_VAI_TRO PRIMARY KEY (MaVaiTro),
    CONSTRAINT UQ_VAI_TRO_TenVaiTro UNIQUE (TenVaiTro)
);
GO

CREATE TABLE dbo.NHAN_VIEN (
    MaNV VARCHAR(10) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    NgaySinh DATE NULL,
    GioiTinh VARCHAR(10) NULL,
    SDT VARCHAR(15) NOT NULL,
    Email VARCHAR(100) NULL,
    DiaChi NVARCHAR(255) NULL,
    NgayVaoLam DATE NOT NULL CONSTRAINT DF_NHAN_VIEN_NgayVaoLam DEFAULT (CONVERT(DATE, SYSDATETIME())),
    LuongCoBan DECIMAL(18,2) NOT NULL CONSTRAINT DF_NHAN_VIEN_LuongCoBan DEFAULT (0),
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_NHAN_VIEN_TrangThai DEFAULT ('ACTIVE'),
    CONSTRAINT PK_NHAN_VIEN PRIMARY KEY (MaNV),
    CONSTRAINT UQ_NHAN_VIEN_SDT UNIQUE (SDT),
    CONSTRAINT CK_NHAN_VIEN_GioiTinh CHECK (GioiTinh IS NULL OR GioiTinh IN ('MALE', 'FEMALE', 'OTHER')),
    CONSTRAINT CK_NHAN_VIEN_LuongCoBan CHECK (LuongCoBan >= 0),
    CONSTRAINT CK_NHAN_VIEN_TrangThai CHECK (TrangThai IN ('ACTIVE', 'INACTIVE'))
);
GO

CREATE TABLE dbo.KHACH_HANG (
    MaKH VARCHAR(10) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    Email VARCHAR(100) NULL,
    DiaChi NVARCHAR(255) NULL,
    NgaySinh DATE NULL,
    DiemTichLuy INT NOT NULL CONSTRAINT DF_KHACH_HANG_DiemTichLuy DEFAULT (0),
    HangThanhVien VARCHAR(20) NOT NULL CONSTRAINT DF_KHACH_HANG_HangThanhVien DEFAULT ('BRONZE'),
    NgayDangKy DATETIME2(0) NOT NULL CONSTRAINT DF_KHACH_HANG_NgayDangKy DEFAULT (SYSDATETIME()),
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_KHACH_HANG_TrangThai DEFAULT ('ACTIVE'),
    CONSTRAINT PK_KHACH_HANG PRIMARY KEY (MaKH),
    CONSTRAINT UQ_KHACH_HANG_SDT UNIQUE (SDT),
    CONSTRAINT CK_KHACH_HANG_DiemTichLuy CHECK (DiemTichLuy >= 0),
    CONSTRAINT CK_KHACH_HANG_HangThanhVien CHECK (HangThanhVien IN ('BRONZE', 'SILVER', 'GOLD', 'DIAMOND')),
    CONSTRAINT CK_KHACH_HANG_TrangThai CHECK (TrangThai IN ('ACTIVE', 'INACTIVE'))
);
GO

CREATE TABLE dbo.TAI_KHOAN (
    MaTK INT IDENTITY(1,1) NOT NULL,
    TenDangNhap VARCHAR(50) NOT NULL,
    MatKhauHash VARCHAR(255) NOT NULL,
    MaVaiTro VARCHAR(20) NOT NULL,
    MaNV VARCHAR(10) NULL,
    MaKH VARCHAR(10) NULL,
    LanDangNhapCuoi DATETIME2(0) NULL,
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_TAI_KHOAN_TrangThai DEFAULT ('ACTIVE'),
    NgayTao DATETIME2(0) NOT NULL CONSTRAINT DF_TAI_KHOAN_NgayTao DEFAULT (SYSDATETIME()),
    CONSTRAINT PK_TAI_KHOAN PRIMARY KEY (MaTK),
    CONSTRAINT UQ_TAI_KHOAN_TenDangNhap UNIQUE (TenDangNhap),
    CONSTRAINT FK_TAI_KHOAN_VAI_TRO FOREIGN KEY (MaVaiTro) REFERENCES dbo.VAI_TRO (MaVaiTro),
    CONSTRAINT FK_TAI_KHOAN_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN (MaNV),
    CONSTRAINT FK_TAI_KHOAN_KHACH_HANG FOREIGN KEY (MaKH) REFERENCES dbo.KHACH_HANG (MaKH),
    CONSTRAINT CK_TAI_KHOAN_OwnerExclusive CHECK (
        (MaNV IS NOT NULL AND MaKH IS NULL)
        OR (MaNV IS NULL AND MaKH IS NOT NULL)
    ),
    CONSTRAINT CK_TAI_KHOAN_TrangThai CHECK (TrangThai IN ('ACTIVE', 'LOCKED', 'INACTIVE'))
);
GO

CREATE UNIQUE INDEX UX_TAI_KHOAN_MaNV
    ON dbo.TAI_KHOAN (MaNV)
    WHERE MaNV IS NOT NULL;
GO

CREATE UNIQUE INDEX UX_TAI_KHOAN_MaKH
    ON dbo.TAI_KHOAN (MaKH)
    WHERE MaKH IS NOT NULL;
GO
