SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

CREATE TABLE dbo.LOAI_SAN_PHAM (
    MaLoai VARCHAR(10) NOT NULL,
    TenLoai NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255) NULL,
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_LOAI_SAN_PHAM_TrangThai DEFAULT ('ACTIVE'),
    CONSTRAINT PK_LOAI_SAN_PHAM PRIMARY KEY (MaLoai),
    CONSTRAINT UQ_LOAI_SAN_PHAM_TenLoai UNIQUE (TenLoai),
    CONSTRAINT CK_LOAI_SAN_PHAM_TrangThai CHECK (TrangThai IN ('ACTIVE', 'INACTIVE'))
);
GO

CREATE TABLE dbo.SAN_PHAM (
    MaSP VARCHAR(10) NOT NULL,
    TenSP NVARCHAR(150) NOT NULL,
    MaVach VARCHAR(30) NULL,
    DonViTinh NVARCHAR(20) NOT NULL,
    GiaBan DECIMAL(18,2) NOT NULL,
    MucTonToiThieu INT NOT NULL CONSTRAINT DF_SAN_PHAM_MucTonToiThieu DEFAULT (0),
    MaLoai VARCHAR(10) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_SAN_PHAM_TrangThai DEFAULT ('ACTIVE'),
    CONSTRAINT PK_SAN_PHAM PRIMARY KEY (MaSP),
    CONSTRAINT FK_SAN_PHAM_LOAI_SAN_PHAM FOREIGN KEY (MaLoai) REFERENCES dbo.LOAI_SAN_PHAM (MaLoai),
    CONSTRAINT CK_SAN_PHAM_GiaBan CHECK (GiaBan > 0),
    CONSTRAINT CK_SAN_PHAM_MucTonToiThieu CHECK (MucTonToiThieu >= 0),
    CONSTRAINT CK_SAN_PHAM_TrangThai CHECK (TrangThai IN ('ACTIVE', 'INACTIVE'))
);
GO

CREATE UNIQUE INDEX UX_SAN_PHAM_MaVach
    ON dbo.SAN_PHAM (MaVach)
    WHERE MaVach IS NOT NULL;
GO

CREATE INDEX IX_SAN_PHAM_MaLoai_TrangThai
    ON dbo.SAN_PHAM (MaLoai, TrangThai);
GO

CREATE TABLE dbo.KHUYEN_MAI (
    MaKM VARCHAR(12) NOT NULL,
    TenKM NVARCHAR(150) NOT NULL,
    LoaiKM VARCHAR(20) NOT NULL,
    GiaTri DECIMAL(18,2) NOT NULL,
    GiaTriDonToiThieu DECIMAL(18,2) NOT NULL CONSTRAINT DF_KHUYEN_MAI_GiaTriDonToiThieu DEFAULT (0),
    MucGiamToiDa DECIMAL(18,2) NULL,
    NgayBatDau DATETIME2(0) NOT NULL,
    NgayKetThuc DATETIME2(0) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_KHUYEN_MAI_TrangThai DEFAULT ('ACTIVE'),
    CONSTRAINT PK_KHUYEN_MAI PRIMARY KEY (MaKM),
    CONSTRAINT CK_KHUYEN_MAI_LoaiKM CHECK (LoaiKM IN ('PERCENT', 'AMOUNT')),
    CONSTRAINT CK_KHUYEN_MAI_GiaTri CHECK (GiaTri > 0 AND (LoaiKM <> 'PERCENT' OR GiaTri <= 100)),
    CONSTRAINT CK_KHUYEN_MAI_GiaTriDonToiThieu CHECK (GiaTriDonToiThieu >= 0),
    CONSTRAINT CK_KHUYEN_MAI_MucGiamToiDa CHECK (MucGiamToiDa IS NULL OR MucGiamToiDa > 0),
    CONSTRAINT CK_KHUYEN_MAI_ThoiGian CHECK (NgayKetThuc > NgayBatDau),
    CONSTRAINT CK_KHUYEN_MAI_TrangThai CHECK (TrangThai IN ('ACTIVE', 'INACTIVE'))
);
GO

CREATE INDEX IX_KHUYEN_MAI_TrangThai_ThoiGian
    ON dbo.KHUYEN_MAI (TrangThai, NgayBatDau, NgayKetThuc);
GO

CREATE TABLE dbo.KHUYEN_MAI_SAN_PHAM (
    MaKM VARCHAR(12) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    CONSTRAINT PK_KHUYEN_MAI_SAN_PHAM PRIMARY KEY (MaKM, MaSP),
    CONSTRAINT FK_KHUYEN_MAI_SAN_PHAM_KHUYEN_MAI FOREIGN KEY (MaKM) REFERENCES dbo.KHUYEN_MAI (MaKM),
    CONSTRAINT FK_KHUYEN_MAI_SAN_PHAM_SAN_PHAM FOREIGN KEY (MaSP) REFERENCES dbo.SAN_PHAM (MaSP)
);
GO

CREATE INDEX IX_KHUYEN_MAI_SAN_PHAM_MaSP
    ON dbo.KHUYEN_MAI_SAN_PHAM (MaSP);
GO

CREATE TABLE dbo.NHA_CUNG_CAP (
    MaNCC VARCHAR(10) NOT NULL,
    TenNCC NVARCHAR(150) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    Email VARCHAR(100) NULL,
    DiaChi NVARCHAR(255) NULL,
    MaSoThue VARCHAR(20) NULL,
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_NHA_CUNG_CAP_TrangThai DEFAULT ('ACTIVE'),
    CONSTRAINT PK_NHA_CUNG_CAP PRIMARY KEY (MaNCC),
    CONSTRAINT UQ_NHA_CUNG_CAP_SDT UNIQUE (SDT),
    CONSTRAINT CK_NHA_CUNG_CAP_TrangThai CHECK (TrangThai IN ('ACTIVE', 'INACTIVE'))
);
GO

CREATE UNIQUE INDEX UX_NHA_CUNG_CAP_MaSoThue
    ON dbo.NHA_CUNG_CAP (MaSoThue)
    WHERE MaSoThue IS NOT NULL;
GO
