SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

CREATE TABLE dbo.CA_LAM_VIEC (
    MaCa BIGINT IDENTITY(1,1) NOT NULL,
    MaNV VARCHAR(10) NOT NULL,
    GioBatDau DATETIME2(0) NOT NULL CONSTRAINT DF_CA_LAM_VIEC_GioBatDau DEFAULT (SYSDATETIME()),
    GioKetThuc DATETIME2(0) NULL,
    TienDauCa DECIMAL(18,2) NOT NULL CONSTRAINT DF_CA_LAM_VIEC_TienDauCa DEFAULT (0),
    TienCuoiCa DECIMAL(18,2) NULL,
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_CA_LAM_VIEC_TrangThai DEFAULT ('OPEN'),
    GhiChu NVARCHAR(255) NULL,
    CONSTRAINT PK_CA_LAM_VIEC PRIMARY KEY (MaCa),
    CONSTRAINT FK_CA_LAM_VIEC_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN (MaNV),
    CONSTRAINT CK_CA_LAM_VIEC_GioKetThuc CHECK (GioKetThuc IS NULL OR GioKetThuc >= GioBatDau),
    CONSTRAINT CK_CA_LAM_VIEC_TienDauCa CHECK (TienDauCa >= 0),
    CONSTRAINT CK_CA_LAM_VIEC_TienCuoiCa CHECK (TienCuoiCa IS NULL OR TienCuoiCa >= 0),
    CONSTRAINT CK_CA_LAM_VIEC_TrangThai CHECK (TrangThai IN ('OPEN', 'CLOSED'))
);
GO

CREATE INDEX IX_CA_LAM_VIEC_MaNV_TrangThai
    ON dbo.CA_LAM_VIEC (MaNV, TrangThai);
GO

CREATE TABLE dbo.PHIEU_NHAP (
    MaPN VARCHAR(15) NOT NULL,
    NgayNhap DATETIME2(0) NOT NULL CONSTRAINT DF_PHIEU_NHAP_NgayNhap DEFAULT (SYSDATETIME()),
    MaNV VARCHAR(10) NOT NULL,
    MaNCC VARCHAR(10) NOT NULL,
    TongTien DECIMAL(18,2) NOT NULL CONSTRAINT DF_PHIEU_NHAP_TongTien DEFAULT (0),
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_PHIEU_NHAP_TrangThai DEFAULT ('DRAFT'),
    NgayXacNhan DATETIME2(0) NULL,
    GhiChu NVARCHAR(255) NULL,
    CONSTRAINT PK_PHIEU_NHAP PRIMARY KEY (MaPN),
    CONSTRAINT FK_PHIEU_NHAP_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN (MaNV),
    CONSTRAINT FK_PHIEU_NHAP_NHA_CUNG_CAP FOREIGN KEY (MaNCC) REFERENCES dbo.NHA_CUNG_CAP (MaNCC),
    CONSTRAINT CK_PHIEU_NHAP_TongTien CHECK (TongTien >= 0),
    CONSTRAINT CK_PHIEU_NHAP_TrangThai CHECK (TrangThai IN ('DRAFT', 'CONFIRMED', 'CANCELLED'))
);
GO

CREATE INDEX IX_PHIEU_NHAP_MaNCC_NgayNhap
    ON dbo.PHIEU_NHAP (MaNCC, NgayNhap DESC);
GO

CREATE TABLE dbo.LO_HANG (
    MaLo VARCHAR(20) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    SoLo VARCHAR(50) NOT NULL,
    NgaySanXuat DATE NULL,
    HanSuDung DATE NULL,
    GiaNhap DECIMAL(18,2) NOT NULL,
    SoLuongTon INT NOT NULL CONSTRAINT DF_LO_HANG_SoLuongTon DEFAULT (0),
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_LO_HANG_TrangThai DEFAULT ('ACTIVE'),
    CONSTRAINT PK_LO_HANG PRIMARY KEY (MaLo),
    CONSTRAINT UQ_LO_HANG_MaSP_SoLo UNIQUE (MaSP, SoLo),
    CONSTRAINT FK_LO_HANG_SAN_PHAM FOREIGN KEY (MaSP) REFERENCES dbo.SAN_PHAM (MaSP),
    CONSTRAINT CK_LO_HANG_HanSuDung CHECK (HanSuDung IS NULL OR NgaySanXuat IS NULL OR HanSuDung > NgaySanXuat),
    CONSTRAINT CK_LO_HANG_GiaNhap CHECK (GiaNhap >= 0),
    CONSTRAINT CK_LO_HANG_SoLuongTon CHECK (SoLuongTon >= 0),
    CONSTRAINT CK_LO_HANG_TrangThai CHECK (TrangThai IN ('ACTIVE', 'BLOCKED', 'EXPIRED'))
);
GO

CREATE INDEX IX_LO_HANG_FEFO
    ON dbo.LO_HANG (MaSP, TrangThai, HanSuDung)
    INCLUDE (SoLuongTon, GiaNhap, SoLo);
GO

CREATE TABLE dbo.CHI_TIET_PHIEU_NHAP (
    MaCTPN BIGINT IDENTITY(1,1) NOT NULL,
    MaPN VARCHAR(15) NOT NULL,
    MaLo VARCHAR(20) NOT NULL,
    SoLuong INT NOT NULL,
    DonGiaNhap DECIMAL(18,2) NOT NULL,
    ThanhTien AS (CONVERT(DECIMAL(18,2), SoLuong * DonGiaNhap)) PERSISTED,
    CONSTRAINT PK_CHI_TIET_PHIEU_NHAP PRIMARY KEY (MaCTPN),
    CONSTRAINT UQ_CHI_TIET_PHIEU_NHAP_MaPN_MaLo UNIQUE (MaPN, MaLo),
    CONSTRAINT FK_CHI_TIET_PHIEU_NHAP_PHIEU_NHAP FOREIGN KEY (MaPN) REFERENCES dbo.PHIEU_NHAP (MaPN),
    CONSTRAINT FK_CHI_TIET_PHIEU_NHAP_LO_HANG FOREIGN KEY (MaLo) REFERENCES dbo.LO_HANG (MaLo),
    CONSTRAINT CK_CHI_TIET_PHIEU_NHAP_SoLuong CHECK (SoLuong > 0),
    CONSTRAINT CK_CHI_TIET_PHIEU_NHAP_DonGiaNhap CHECK (DonGiaNhap >= 0)
);
GO

CREATE TABLE dbo.KIEM_KE (
    MaKK VARCHAR(15) NOT NULL,
    NgayKiemKe DATETIME2(0) NOT NULL CONSTRAINT DF_KIEM_KE_NgayKiemKe DEFAULT (SYSDATETIME()),
    MaNV VARCHAR(10) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_KIEM_KE_TrangThai DEFAULT ('DRAFT'),
    GhiChu NVARCHAR(255) NULL,
    CONSTRAINT PK_KIEM_KE PRIMARY KEY (MaKK),
    CONSTRAINT FK_KIEM_KE_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN (MaNV),
    CONSTRAINT CK_KIEM_KE_TrangThai CHECK (TrangThai IN ('DRAFT', 'APPROVED', 'CANCELLED'))
);
GO

CREATE INDEX IX_KIEM_KE_TrangThai_NgayKiemKe
    ON dbo.KIEM_KE (TrangThai, NgayKiemKe DESC);
GO

CREATE TABLE dbo.CHI_TIET_KIEM_KE (
    MaKK VARCHAR(15) NOT NULL,
    MaLo VARCHAR(20) NOT NULL,
    SoLuongHeThong INT NOT NULL,
    SoLuongThucTe INT NOT NULL,
    ChenhLech AS (SoLuongThucTe - SoLuongHeThong) PERSISTED,
    LyDo NVARCHAR(255) NULL,
    CONSTRAINT PK_CHI_TIET_KIEM_KE PRIMARY KEY (MaKK, MaLo),
    CONSTRAINT FK_CHI_TIET_KIEM_KE_KIEM_KE FOREIGN KEY (MaKK) REFERENCES dbo.KIEM_KE (MaKK),
    CONSTRAINT FK_CHI_TIET_KIEM_KE_LO_HANG FOREIGN KEY (MaLo) REFERENCES dbo.LO_HANG (MaLo),
    CONSTRAINT CK_CHI_TIET_KIEM_KE_SoLuongHeThong CHECK (SoLuongHeThong >= 0),
    CONSTRAINT CK_CHI_TIET_KIEM_KE_SoLuongThucTe CHECK (SoLuongThucTe >= 0)
);
GO

CREATE TABLE dbo.GIAO_DICH_KHO (
    MaGiaoDich BIGINT IDENTITY(1,1) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    MaLo VARCHAR(20) NOT NULL,
    LoaiGiaoDich VARCHAR(30) NOT NULL,
    SoLuongBienDong INT NOT NULL,
    ThoiGian DATETIME2(0) NOT NULL CONSTRAINT DF_GIAO_DICH_KHO_ThoiGian DEFAULT (SYSDATETIME()),
    MaThamChieu VARCHAR(20) NULL,
    MaNV VARCHAR(10) NULL,
    GhiChu NVARCHAR(255) NULL,
    CONSTRAINT PK_GIAO_DICH_KHO PRIMARY KEY (MaGiaoDich),
    CONSTRAINT FK_GIAO_DICH_KHO_SAN_PHAM FOREIGN KEY (MaSP) REFERENCES dbo.SAN_PHAM (MaSP),
    CONSTRAINT FK_GIAO_DICH_KHO_LO_HANG FOREIGN KEY (MaLo) REFERENCES dbo.LO_HANG (MaLo),
    CONSTRAINT FK_GIAO_DICH_KHO_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN (MaNV),
    CONSTRAINT CK_GIAO_DICH_KHO_LoaiGiaoDich CHECK (LoaiGiaoDich IN ('IMPORT', 'SALE', 'SALE_CANCEL', 'RETURN', 'ADJUSTMENT')),
    CONSTRAINT CK_GIAO_DICH_KHO_SoLuongBienDong CHECK (SoLuongBienDong <> 0)
);
GO

CREATE INDEX IX_GIAO_DICH_KHO_MaLo_ThoiGian
    ON dbo.GIAO_DICH_KHO (MaLo, ThoiGian DESC);
GO

CREATE INDEX IX_GIAO_DICH_KHO_MaThamChieu
    ON dbo.GIAO_DICH_KHO (MaThamChieu)
    WHERE MaThamChieu IS NOT NULL;
GO
