SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

CREATE TABLE dbo.HOA_DON (
    MaHD VARCHAR(15) NOT NULL,
    NgayLap DATETIME2(0) NOT NULL CONSTRAINT DF_HOA_DON_NgayLap DEFAULT (SYSDATETIME()),
    MaCa BIGINT NOT NULL,
    MaKH VARCHAR(10) NULL,
    TongTienHang DECIMAL(18,2) NOT NULL CONSTRAINT DF_HOA_DON_TongTienHang DEFAULT (0),
    TongGiamGia DECIMAL(18,2) NOT NULL CONSTRAINT DF_HOA_DON_TongGiamGia DEFAULT (0),
    TongThanhToan DECIMAL(18,2) NOT NULL CONSTRAINT DF_HOA_DON_TongThanhToan DEFAULT (0),
    DiemSuDung INT NOT NULL CONSTRAINT DF_HOA_DON_DiemSuDung DEFAULT (0),
    DiemTichLuy INT NOT NULL CONSTRAINT DF_HOA_DON_DiemTichLuy DEFAULT (0),
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_HOA_DON_TrangThai DEFAULT ('DRAFT'),
    GhiChu NVARCHAR(255) NULL,
    CONSTRAINT PK_HOA_DON PRIMARY KEY (MaHD),
    CONSTRAINT FK_HOA_DON_CA_LAM_VIEC FOREIGN KEY (MaCa) REFERENCES dbo.CA_LAM_VIEC (MaCa),
    CONSTRAINT FK_HOA_DON_KHACH_HANG FOREIGN KEY (MaKH) REFERENCES dbo.KHACH_HANG (MaKH),
    CONSTRAINT CK_HOA_DON_TongTienHang CHECK (TongTienHang >= 0),
    CONSTRAINT CK_HOA_DON_TongGiamGia CHECK (TongGiamGia >= 0),
    CONSTRAINT CK_HOA_DON_TongThanhToan CHECK (TongThanhToan >= 0),
    CONSTRAINT CK_HOA_DON_DiemSuDung CHECK (DiemSuDung >= 0),
    CONSTRAINT CK_HOA_DON_DiemTichLuy CHECK (DiemTichLuy >= 0),
    CONSTRAINT CK_HOA_DON_TrangThai CHECK (TrangThai IN ('DRAFT', 'PAID', 'CANCELLED', 'REFUNDED'))
);
GO

CREATE INDEX IX_HOA_DON_MaCa_NgayLap
    ON dbo.HOA_DON (MaCa, NgayLap DESC);
GO

CREATE INDEX IX_HOA_DON_MaKH_NgayLap
    ON dbo.HOA_DON (MaKH, NgayLap DESC)
    WHERE MaKH IS NOT NULL;
GO

CREATE TABLE dbo.CHI_TIET_HOA_DON (
    MaCTHD BIGINT IDENTITY(1,1) NOT NULL,
    MaHD VARCHAR(15) NOT NULL,
    MaSP VARCHAR(10) NOT NULL,
    MaKM VARCHAR(12) NULL,
    SoLuong INT NOT NULL,
    DonGiaBan DECIMAL(18,2) NOT NULL,
    TienGiam DECIMAL(18,2) NOT NULL CONSTRAINT DF_CHI_TIET_HOA_DON_TienGiam DEFAULT (0),
    ThanhTien AS (CONVERT(DECIMAL(18,2), (SoLuong * DonGiaBan) - TienGiam)) PERSISTED,
    CONSTRAINT PK_CHI_TIET_HOA_DON PRIMARY KEY (MaCTHD),
    CONSTRAINT UQ_CHI_TIET_HOA_DON_MaHD_MaSP UNIQUE (MaHD, MaSP),
    CONSTRAINT FK_CHI_TIET_HOA_DON_HOA_DON FOREIGN KEY (MaHD) REFERENCES dbo.HOA_DON (MaHD),
    CONSTRAINT FK_CHI_TIET_HOA_DON_SAN_PHAM FOREIGN KEY (MaSP) REFERENCES dbo.SAN_PHAM (MaSP),
    CONSTRAINT FK_CHI_TIET_HOA_DON_KHUYEN_MAI FOREIGN KEY (MaKM) REFERENCES dbo.KHUYEN_MAI (MaKM),
    CONSTRAINT CK_CHI_TIET_HOA_DON_SoLuong CHECK (SoLuong > 0),
    CONSTRAINT CK_CHI_TIET_HOA_DON_DonGiaBan CHECK (DonGiaBan > 0),
    CONSTRAINT CK_CHI_TIET_HOA_DON_TienGiam CHECK (TienGiam >= 0 AND TienGiam <= SoLuong * DonGiaBan)
);
GO

CREATE TABLE dbo.CHI_TIET_XUAT_LO (
    MaCTHD BIGINT NOT NULL,
    MaLo VARCHAR(20) NOT NULL,
    SoLuong INT NOT NULL,
    CONSTRAINT PK_CHI_TIET_XUAT_LO PRIMARY KEY (MaCTHD, MaLo),
    CONSTRAINT FK_CHI_TIET_XUAT_LO_CHI_TIET_HOA_DON FOREIGN KEY (MaCTHD) REFERENCES dbo.CHI_TIET_HOA_DON (MaCTHD),
    CONSTRAINT FK_CHI_TIET_XUAT_LO_LO_HANG FOREIGN KEY (MaLo) REFERENCES dbo.LO_HANG (MaLo),
    CONSTRAINT CK_CHI_TIET_XUAT_LO_SoLuong CHECK (SoLuong > 0)
);
GO

CREATE INDEX IX_CHI_TIET_XUAT_LO_MaLo
    ON dbo.CHI_TIET_XUAT_LO (MaLo);
GO

CREATE TABLE dbo.THANH_TOAN (
    MaThanhToan BIGINT IDENTITY(1,1) NOT NULL,
    MaHD VARCHAR(15) NOT NULL,
    ThoiGian DATETIME2(0) NOT NULL CONSTRAINT DF_THANH_TOAN_ThoiGian DEFAULT (SYSDATETIME()),
    PhuongThuc VARCHAR(20) NOT NULL,
    SoTien DECIMAL(18,2) NOT NULL,
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_THANH_TOAN_TrangThai DEFAULT ('SUCCESS'),
    MaGiaoDichNgoai VARCHAR(100) NULL,
    CONSTRAINT PK_THANH_TOAN PRIMARY KEY (MaThanhToan),
    CONSTRAINT FK_THANH_TOAN_HOA_DON FOREIGN KEY (MaHD) REFERENCES dbo.HOA_DON (MaHD),
    CONSTRAINT CK_THANH_TOAN_PhuongThuc CHECK (PhuongThuc IN ('CASH', 'CARD', 'TRANSFER', 'EWALLET')),
    CONSTRAINT CK_THANH_TOAN_SoTien CHECK (SoTien > 0),
    CONSTRAINT CK_THANH_TOAN_TrangThai CHECK (TrangThai IN ('SUCCESS', 'FAILED', 'REFUNDED'))
);
GO

CREATE INDEX IX_THANH_TOAN_MaHD_ThoiGian
    ON dbo.THANH_TOAN (MaHD, ThoiGian DESC);
GO

CREATE TABLE dbo.PHIEU_TRA (
    MaPT VARCHAR(15) NOT NULL,
    MaHD VARCHAR(15) NOT NULL,
    MaNV VARCHAR(10) NOT NULL,
    NgayTra DATETIME2(0) NOT NULL CONSTRAINT DF_PHIEU_TRA_NgayTra DEFAULT (SYSDATETIME()),
    LyDo NVARCHAR(255) NOT NULL,
    TongTienHoan DECIMAL(18,2) NOT NULL CONSTRAINT DF_PHIEU_TRA_TongTienHoan DEFAULT (0),
    TrangThai VARCHAR(20) NOT NULL CONSTRAINT DF_PHIEU_TRA_TrangThai DEFAULT ('CREATED'),
    CONSTRAINT PK_PHIEU_TRA PRIMARY KEY (MaPT),
    CONSTRAINT FK_PHIEU_TRA_HOA_DON FOREIGN KEY (MaHD) REFERENCES dbo.HOA_DON (MaHD),
    CONSTRAINT FK_PHIEU_TRA_NHAN_VIEN FOREIGN KEY (MaNV) REFERENCES dbo.NHAN_VIEN (MaNV),
    CONSTRAINT CK_PHIEU_TRA_TongTienHoan CHECK (TongTienHoan >= 0),
    CONSTRAINT CK_PHIEU_TRA_TrangThai CHECK (TrangThai IN ('CREATED', 'COMPLETED', 'CANCELLED'))
);
GO

CREATE INDEX IX_PHIEU_TRA_MaHD_NgayTra
    ON dbo.PHIEU_TRA (MaHD, NgayTra DESC);
GO

CREATE TABLE dbo.CHI_TIET_PHIEU_TRA (
    MaPT VARCHAR(15) NOT NULL,
    MaCTHD BIGINT NOT NULL,
    MaLo VARCHAR(20) NOT NULL,
    SoLuongTra INT NOT NULL,
    TienHoan DECIMAL(18,2) NOT NULL,
    TinhTrangHang VARCHAR(20) NOT NULL CONSTRAINT DF_CHI_TIET_PHIEU_TRA_TinhTrangHang DEFAULT ('RESALABLE'),
    CONSTRAINT PK_CHI_TIET_PHIEU_TRA PRIMARY KEY (MaPT, MaCTHD, MaLo),
    CONSTRAINT FK_CHI_TIET_PHIEU_TRA_PHIEU_TRA FOREIGN KEY (MaPT) REFERENCES dbo.PHIEU_TRA (MaPT),
    CONSTRAINT FK_CHI_TIET_PHIEU_TRA_CHI_TIET_XUAT_LO FOREIGN KEY (MaCTHD, MaLo)
        REFERENCES dbo.CHI_TIET_XUAT_LO (MaCTHD, MaLo),
    CONSTRAINT CK_CHI_TIET_PHIEU_TRA_SoLuongTra CHECK (SoLuongTra > 0),
    CONSTRAINT CK_CHI_TIET_PHIEU_TRA_TienHoan CHECK (TienHoan >= 0),
    CONSTRAINT CK_CHI_TIET_PHIEU_TRA_TinhTrangHang CHECK (TinhTrangHang IN ('RESALABLE', 'DAMAGED'))
);
GO

CREATE INDEX IX_CHI_TIET_PHIEU_TRA_MaCTHD_MaLo
    ON dbo.CHI_TIET_PHIEU_TRA (MaCTHD, MaLo);
GO

CREATE TABLE dbo.NHAT_KY_HE_THONG (
    MaNhatKy BIGINT IDENTITY(1,1) NOT NULL,
    MaTK INT NULL,
    HanhDong VARCHAR(50) NOT NULL,
    TenBang VARCHAR(128) NOT NULL,
    MaBanGhi VARCHAR(100) NULL,
    DuLieuCu NVARCHAR(MAX) NULL,
    DuLieuMoi NVARCHAR(MAX) NULL,
    ThoiGian DATETIME2(0) NOT NULL CONSTRAINT DF_NHAT_KY_HE_THONG_ThoiGian DEFAULT (SYSDATETIME()),
    DiaChiIP VARCHAR(45) NULL,
    CONSTRAINT PK_NHAT_KY_HE_THONG PRIMARY KEY (MaNhatKy),
    CONSTRAINT FK_NHAT_KY_HE_THONG_TAI_KHOAN FOREIGN KEY (MaTK) REFERENCES dbo.TAI_KHOAN (MaTK)
);
GO

CREATE INDEX IX_NHAT_KY_HE_THONG_ThoiGian
    ON dbo.NHAT_KY_HE_THONG (ThoiGian DESC);
GO

CREATE INDEX IX_NHAT_KY_HE_THONG_MaTK_ThoiGian
    ON dbo.NHAT_KY_HE_THONG (MaTK, ThoiGian DESC)
    WHERE MaTK IS NOT NULL;
GO
